# Generated by Django 2.0.5 on 2018-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ko', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slide_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
