# Generated by Django 2.0.5 on 2018-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0004_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=True, to='openinfradays.ProgramDate')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='openinfradays.ProgramDate'),
        ),
        migrations.AddField(
            model_name='program',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='openinfradays.Room'),
        ),
        migrations.AddField(
            model_name='program',
            name='times',
            field=models.ManyToManyField(blank=True, to='openinfradays.ProgramTime'),
        ),
    ]
